const NATIONS = {
  "Italian": "Italy", 
  "British": "England", 
  "Belgian": "Belgium", 
  "American": "United-States", 
  "German": "Germany", 
  "Dutch": "Netherlands", 
  "Thai": "Thailand", 
  "French": "France", 
  "Spanish": "Spain", 
  "New Zealander": "New-Zealand", 
  "Swedish": "Sweden", 
  "Brazilian": "Brazil", 
  "Hungarian": "Hungary", 
  "Danish": "Denmark", 
  "Monegasque": "Monaco", 
  "Canadian": "Canada", 
  "Austrian": "Austria", 
  "Argentine": "Argentina", 
  "South African": "South-Africa", 
  "Finnish": "Finland", 
  "Australian": "Australia", 
  "Swiss": "Switzerland", 
  "Irish": "Ireland", 
  "Portuguese": "Portugal", 
  "Uruguayan": "Uruguay", 
  "Venezuelan": "Venezuela", 
  "Indian": "India", 
  "Argentine-Italian": "Aregentina", 
  "Czech": "Czech-Republic", 
  "East German": "Germany", 
  "Japanese": "Japan", 
  "Colombian": "Columbia", 
  "Mexican": "Mexico", 
  "Indonesian": "Indonesia", 
  "Rhodesian": "Zimbabwe", 
  "Polish": "Poland", 
  "Russian": "Russia", 
  "Chilean": "Chile", 
  "American-Italian": "United-States", 
  "Liechtensteiner": "Liechtenstein", 
  "Malaysian": "Malaysia", 
  "New Zealand": "New-Zealand",
  "Belgium": "Belgium", 
  "Hong Kong": "Hong Kong"
}

export {NATIONS}